[package]
name = "uurlog"
version = "0.1.0"
authors = ["Maarten de Vries <maarten@de-vri.es>"]
edition = "2018"

[dev-dependencies]
assert2 = "0.2.1"
structopt = "0.3.14"

[dependencies]
env_logger = "0.7.1"
gregorian  = "0.1.0"
log        = "0.4.8"
structopt  = "0.3.14"
yansi      = "0.5.0"
